<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>13.0</LangVersion>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace></RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Collections.Immutable" Version="9.0.9" />
        <PackageReference Include="System.Memory" Version="4.6.0" />
        <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PowerEmit\PowerEmit.csproj" />
    </ItemGroup>

</Project>
