using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using SourceGeneratorToolkit;

namespace PowerEmit.Generators.Internal;

[Generator(LanguageNames.CSharp)]
internal class OperandFormatterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(EmitAttribute);
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            "PowerEmit.Internals.OperandFormatter+OperandFormatterAttribute",
            Predicate,
            Transform)
            .Collect();
        context.RegisterSourceOutput(source, Emit);
    }

    private static void EmitAttribute(IncrementalGeneratorPostInitializationContext context) =>
        context.AddSource(
            "OperandFormatter.Attribute.g.cs",
            """
            // <auto-generated>
            // This (.cs) file is generated by source generator.
            // Do not change it. change the PowerEmit.Generators.Internal.OperandFormatterGenerator instead.
            // </auto-generated>
            namespace PowerEmit.Internals;

            partial class OperandFormatter
            {
                [AttributeUsage(AttributeTargets.Class)]
                private sealed class OperandFormatterAttribute : Attribute;
            }

            """);

    private static bool Predicate(SyntaxNode node, CancellationToken token) => true;

    private static TypeMap Transform(GeneratorAttributeSyntaxContext context, CancellationToken token)
    {
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var name = symbol.ToDisplayString();
        var operandType = symbol.BaseType!.TypeArguments[0].ToDisplayString();
        return new(name, operandType);
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<TypeMap> typeMaps)
    {
        var sb = new SourceBuilderSlim();
        sb.AppendLine($$"""
            // <auto-generated>
            // This (.cs) file is generated by source generator.
            // Do not change it. change the PowerEmit.Generators.Internal.OperandFormatterGenerator instead.
            // </auto-generated>
            namespace PowerEmit.Internals;

            partial class OperandFormatter
            {
                static OperandFormatter()
                {
                    {{typeMaps.Select(x => $"Strategy<{x.TargetOperandType}>.Instance = new {x.TypeName}();").PreserveIndent()}}
                }
            }
            """);

        var source = sb.Build();
        context.AddSource(
            "OperandFormatter.StaticConstructor.g.cs",
            source);
    }


    private record TypeMap(string TypeName, string TargetOperandType);
}
