<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>14.0</LangVersion>
        <Nullable>enable</Nullable>
        <OutputType>library</OutputType>
        <Deterministic>true</Deterministic>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>

        <IsRoslynComponent>true</IsRoslynComponent>
        <AnalyzerLanguage>cs</AnalyzerLanguage>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="akanse.SourceGeneratorToolkit" Version="0.1.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>


</Project>
