// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using Xunit;

namespace PowerEmit
{
    public partial class InstTest
    {
        [Theory]
        [MemberData(nameof(GetTestCases_Basic))]
        public void Emit_Basic(TestCase testCase)
            => EmitCore(testCase);


        public static TheoryData<TestCase> GetTestCases_Basic() =>
            [
            CreateTestCase("nop",
                Inst.Nop(),
                gen => gen.Emit(OpCodes.Nop)
                ),

            CreateTestCase("break",
                Inst.Break(),
                gen => gen.Emit(OpCodes.Break)
                ),

            CreateTestCase("ldarg.0",
                Inst.Ldarg_0(),
                gen => gen.Emit(OpCodes.Ldarg_0)
                ),

            CreateTestCase("ldarg.1",
                Inst.Ldarg_1(),
                gen => gen.Emit(OpCodes.Ldarg_1)
                ),

            CreateTestCase("ldarg.2",
                Inst.Ldarg_2(),
                gen => gen.Emit(OpCodes.Ldarg_2)
                ),

            CreateTestCase("ldarg.3",
                Inst.Ldarg_3(),
                gen => gen.Emit(OpCodes.Ldarg_3)
                ),

            CreateTestCase("ldloc.0",
                Inst.Ldloc_0(),
                gen => gen.Emit(OpCodes.Ldloc_0)
                ),

            CreateTestCase("ldloc.1",
                Inst.Ldloc_1(),
                gen => gen.Emit(OpCodes.Ldloc_1)
                ),

            CreateTestCase("ldloc.2",
                Inst.Ldloc_2(),
                gen => gen.Emit(OpCodes.Ldloc_2)
                ),

            CreateTestCase("ldloc.3",
                Inst.Ldloc_3(),
                gen => gen.Emit(OpCodes.Ldloc_3)
                ),

            CreateTestCase("stloc.0",
                Inst.Stloc_0(),
                gen => gen.Emit(OpCodes.Stloc_0)
                ),

            CreateTestCase("stloc.1",
                Inst.Stloc_1(),
                gen => gen.Emit(OpCodes.Stloc_1)
                ),

            CreateTestCase("stloc.2",
                Inst.Stloc_2(),
                gen => gen.Emit(OpCodes.Stloc_2)
                ),

            CreateTestCase("stloc.3",
                Inst.Stloc_3(),
                gen => gen.Emit(OpCodes.Stloc_3)
                ),

            CreateTestCase("ldarg.s",
                Inst.Ldarg_S(byte.MaxValue),
                gen => gen.Emit(OpCodes.Ldarg_S, byte.MaxValue)
                ),

            CreateTestCase("ldarga.s",
                Inst.Ldarga_S(byte.MaxValue),
                gen => gen.Emit(OpCodes.Ldarga_S, byte.MaxValue)
                ),

            CreateTestCase("starg.s",
                Inst.Starg_S(byte.MaxValue),
                gen => gen.Emit(OpCodes.Starg_S, byte.MaxValue)
                ),

            CreateTestCase("ldloc.s",
                Inst.Ldloc_S(byte.MaxValue),
                gen => gen.Emit(OpCodes.Ldloc_S, byte.MaxValue)
                ),

            CreateTestCase("ldloca.s",
                Inst.Ldloca_S(byte.MaxValue),
                gen => gen.Emit(OpCodes.Ldloca_S, byte.MaxValue)
                ),

            CreateTestCase("stloc.s",
                Inst.Stloc_S(byte.MaxValue),
                gen => gen.Emit(OpCodes.Stloc_S, byte.MaxValue)
                ),

            CreateTestCase("ldnull",
                Inst.Ldnull(),
                gen => gen.Emit(OpCodes.Ldnull)
                ),

            CreateTestCase("ldc.i4.m1",
                Inst.Ldc_I4_M1(),
                gen => gen.Emit(OpCodes.Ldc_I4_M1)
                ),

            CreateTestCase("ldc.i4.0",
                Inst.Ldc_I4_0(),
                gen => gen.Emit(OpCodes.Ldc_I4_0)
                ),

            CreateTestCase("ldc.i4.1",
                Inst.Ldc_I4_1(),
                gen => gen.Emit(OpCodes.Ldc_I4_1)
                ),

            CreateTestCase("ldc.i4.2",
                Inst.Ldc_I4_2(),
                gen => gen.Emit(OpCodes.Ldc_I4_2)
                ),

            CreateTestCase("ldc.i4.3",
                Inst.Ldc_I4_3(),
                gen => gen.Emit(OpCodes.Ldc_I4_3)
                ),

            CreateTestCase("ldc.i4.4",
                Inst.Ldc_I4_4(),
                gen => gen.Emit(OpCodes.Ldc_I4_4)
                ),

            CreateTestCase("ldc.i4.5",
                Inst.Ldc_I4_5(),
                gen => gen.Emit(OpCodes.Ldc_I4_5)
                ),

            CreateTestCase("ldc.i4.6",
                Inst.Ldc_I4_6(),
                gen => gen.Emit(OpCodes.Ldc_I4_6)
                ),

            CreateTestCase("ldc.i4.7",
                Inst.Ldc_I4_7(),
                gen => gen.Emit(OpCodes.Ldc_I4_7)
                ),

            CreateTestCase("ldc.i4.8",
                Inst.Ldc_I4_8(),
                gen => gen.Emit(OpCodes.Ldc_I4_8)
                ),

            CreateTestCase("ldc.i4.s",
                Inst.Ldc_I4_S(sbyte.MaxValue),
                gen => gen.Emit(OpCodes.Ldc_I4_S, sbyte.MaxValue)
                ),

            CreateTestCase("ldc.i4",
                Inst.Ldc_I4(int.MaxValue),
                gen => gen.Emit(OpCodes.Ldc_I4, int.MaxValue)
                ),

            CreateTestCase("ldc.i8",
                Inst.Ldc_I8(long.MaxValue),
                gen => gen.Emit(OpCodes.Ldc_I8, long.MaxValue)
                ),

            CreateTestCase("ldc.r4",
                Inst.Ldc_R4(float.MaxValue),
                gen => gen.Emit(OpCodes.Ldc_R4, float.MaxValue)
                ),

            CreateTestCase("ldc.r8",
                Inst.Ldc_R8(double.MaxValue),
                gen => gen.Emit(OpCodes.Ldc_R8, double.MaxValue)
                ),

            CreateTestCase("dup",
                Inst.Dup(),
                gen => gen.Emit(OpCodes.Dup)
                ),

            CreateTestCase("pop",
                Inst.Pop(),
                gen => gen.Emit(OpCodes.Pop)
                ),

            CreateTestCase("jmp",
                Inst.Jmp(MockType.MethodInfo),
                gen => gen.Emit(OpCodes.Jmp, MockType.MethodInfo)
                ),

            CreateTestCase("call",
                Inst.Call(MockType.MethodInfo),
                gen => gen.Emit(OpCodes.Call, MockType.MethodInfo)
                ),

            CreateTestCase("ret",
                Inst.Ret(),
                gen => gen.Emit(OpCodes.Ret)
                ),

            CreateTestCase("ldind.i1",
                Inst.Ldind_I1(),
                gen => gen.Emit(OpCodes.Ldind_I1)
                ),

            CreateTestCase("ldind.u1",
                Inst.Ldind_U1(),
                gen => gen.Emit(OpCodes.Ldind_U1)
                ),

            CreateTestCase("ldind.i2",
                Inst.Ldind_I2(),
                gen => gen.Emit(OpCodes.Ldind_I2)
                ),

            CreateTestCase("ldind.u2",
                Inst.Ldind_U2(),
                gen => gen.Emit(OpCodes.Ldind_U2)
                ),

            CreateTestCase("ldind.i4",
                Inst.Ldind_I4(),
                gen => gen.Emit(OpCodes.Ldind_I4)
                ),

            CreateTestCase("ldind.u4",
                Inst.Ldind_U4(),
                gen => gen.Emit(OpCodes.Ldind_U4)
                ),

            CreateTestCase("ldind.i8",
                Inst.Ldind_I8(),
                gen => gen.Emit(OpCodes.Ldind_I8)
                ),

            CreateTestCase("ldind.i",
                Inst.Ldind_I(),
                gen => gen.Emit(OpCodes.Ldind_I)
                ),

            CreateTestCase("ldind.r4",
                Inst.Ldind_R4(),
                gen => gen.Emit(OpCodes.Ldind_R4)
                ),

            CreateTestCase("ldind.r8",
                Inst.Ldind_R8(),
                gen => gen.Emit(OpCodes.Ldind_R8)
                ),

            CreateTestCase("ldind.ref",
                Inst.Ldind_Ref(),
                gen => gen.Emit(OpCodes.Ldind_Ref)
                ),

            CreateTestCase("stind.ref",
                Inst.Stind_Ref(),
                gen => gen.Emit(OpCodes.Stind_Ref)
                ),

            CreateTestCase("stind.i1",
                Inst.Stind_I1(),
                gen => gen.Emit(OpCodes.Stind_I1)
                ),

            CreateTestCase("stind.i2",
                Inst.Stind_I2(),
                gen => gen.Emit(OpCodes.Stind_I2)
                ),

            CreateTestCase("stind.i4",
                Inst.Stind_I4(),
                gen => gen.Emit(OpCodes.Stind_I4)
                ),

            CreateTestCase("stind.i8",
                Inst.Stind_I8(),
                gen => gen.Emit(OpCodes.Stind_I8)
                ),

            CreateTestCase("stind.r4",
                Inst.Stind_R4(),
                gen => gen.Emit(OpCodes.Stind_R4)
                ),

            CreateTestCase("stind.r8",
                Inst.Stind_R8(),
                gen => gen.Emit(OpCodes.Stind_R8)
                ),

            CreateTestCase("add",
                Inst.Add(),
                gen => gen.Emit(OpCodes.Add)
                ),

            CreateTestCase("sub",
                Inst.Sub(),
                gen => gen.Emit(OpCodes.Sub)
                ),

            CreateTestCase("mul",
                Inst.Mul(),
                gen => gen.Emit(OpCodes.Mul)
                ),

            CreateTestCase("div",
                Inst.Div(),
                gen => gen.Emit(OpCodes.Div)
                ),

            CreateTestCase("div.un",
                Inst.Div_Un(),
                gen => gen.Emit(OpCodes.Div_Un)
                ),

            CreateTestCase("rem",
                Inst.Rem(),
                gen => gen.Emit(OpCodes.Rem)
                ),

            CreateTestCase("rem.un",
                Inst.Rem_Un(),
                gen => gen.Emit(OpCodes.Rem_Un)
                ),

            CreateTestCase("and",
                Inst.And(),
                gen => gen.Emit(OpCodes.And)
                ),

            CreateTestCase("or",
                Inst.Or(),
                gen => gen.Emit(OpCodes.Or)
                ),

            CreateTestCase("xor",
                Inst.Xor(),
                gen => gen.Emit(OpCodes.Xor)
                ),

            CreateTestCase("shl",
                Inst.Shl(),
                gen => gen.Emit(OpCodes.Shl)
                ),

            CreateTestCase("shr",
                Inst.Shr(),
                gen => gen.Emit(OpCodes.Shr)
                ),

            CreateTestCase("shr.un",
                Inst.Shr_Un(),
                gen => gen.Emit(OpCodes.Shr_Un)
                ),

            CreateTestCase("neg",
                Inst.Neg(),
                gen => gen.Emit(OpCodes.Neg)
                ),

            CreateTestCase("not",
                Inst.Not(),
                gen => gen.Emit(OpCodes.Not)
                ),

            CreateTestCase("conv.i1",
                Inst.Conv_I1(),
                gen => gen.Emit(OpCodes.Conv_I1)
                ),

            CreateTestCase("conv.i2",
                Inst.Conv_I2(),
                gen => gen.Emit(OpCodes.Conv_I2)
                ),

            CreateTestCase("conv.i4",
                Inst.Conv_I4(),
                gen => gen.Emit(OpCodes.Conv_I4)
                ),

            CreateTestCase("conv.i8",
                Inst.Conv_I8(),
                gen => gen.Emit(OpCodes.Conv_I8)
                ),

            CreateTestCase("conv.r4",
                Inst.Conv_R4(),
                gen => gen.Emit(OpCodes.Conv_R4)
                ),

            CreateTestCase("conv.r8",
                Inst.Conv_R8(),
                gen => gen.Emit(OpCodes.Conv_R8)
                ),

            CreateTestCase("conv.u4",
                Inst.Conv_U4(),
                gen => gen.Emit(OpCodes.Conv_U4)
                ),

            CreateTestCase("conv.u8",
                Inst.Conv_U8(),
                gen => gen.Emit(OpCodes.Conv_U8)
                ),

            CreateTestCase("callvirt",
                Inst.Callvirt(MockType.MethodInfo),
                gen => gen.Emit(OpCodes.Callvirt, MockType.MethodInfo)
                ),

            CreateTestCase("cpobj",
                Inst.Cpobj(MockType.Type),
                gen => gen.Emit(OpCodes.Cpobj, MockType.Type)
                ),

            CreateTestCase("ldobj",
                Inst.Ldobj(MockType.Type),
                gen => gen.Emit(OpCodes.Ldobj, MockType.Type)
                ),

            CreateTestCase("ldstr",
                Inst.Ldstr("foobar"),
                gen => gen.Emit(OpCodes.Ldstr, "foobar")
                ),

            CreateTestCase("newobj",
                Inst.Newobj(MockType.ConstructorInfo),
                gen => gen.Emit(OpCodes.Newobj, MockType.ConstructorInfo)
                ),

            CreateTestCase("castclass",
                Inst.Castclass(MockType.Type),
                gen => gen.Emit(OpCodes.Castclass, MockType.Type)
                ),

            CreateTestCase("isinst",
                Inst.Isinst(MockType.Type),
                gen => gen.Emit(OpCodes.Isinst, MockType.Type)
                ),

            CreateTestCase("conv.r.un",
                Inst.Conv_R_Un(),
                gen => gen.Emit(OpCodes.Conv_R_Un)
                ),

            CreateTestCase("unbox",
                Inst.Unbox(MockType.Type),
                gen => gen.Emit(OpCodes.Unbox, MockType.Type)
                ),

            CreateTestCase("throw",
                Inst.Throw(),
                gen => gen.Emit(OpCodes.Throw)
                ),

            CreateTestCase("ldfld",
                Inst.Ldfld(MockType.InstanceFieldInfo),
                gen => gen.Emit(OpCodes.Ldfld, MockType.InstanceFieldInfo)
                ),

            CreateTestCase("ldflda",
                Inst.Ldflda(MockType.InstanceFieldInfo),
                gen => gen.Emit(OpCodes.Ldflda, MockType.InstanceFieldInfo)
                ),

            CreateTestCase("stfld",
                Inst.Stfld(MockType.InstanceFieldInfo),
                gen => gen.Emit(OpCodes.Stfld, MockType.InstanceFieldInfo)
                ),

            CreateTestCase("ldsfld",
                Inst.Ldsfld(MockType.StaticFieldInfo),
                gen => gen.Emit(OpCodes.Ldsfld, MockType.StaticFieldInfo)
                ),

            CreateTestCase("ldsflda",
                Inst.Ldsflda(MockType.StaticFieldInfo),
                gen => gen.Emit(OpCodes.Ldsflda, MockType.StaticFieldInfo)
                ),

            CreateTestCase("stsfld",
                Inst.Stsfld(MockType.StaticFieldInfo),
                gen => gen.Emit(OpCodes.Stsfld, MockType.StaticFieldInfo)
                ),

            CreateTestCase("stobj",
                Inst.Stobj(MockType.Type),
                gen => gen.Emit(OpCodes.Stobj, MockType.Type)
                ),

            CreateTestCase("conv.ovf.i1.un",
                Inst.Conv_Ovf_I1_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I1_Un)
                ),

            CreateTestCase("conv.ovf.i2.un",
                Inst.Conv_Ovf_I2_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I2_Un)
                ),

            CreateTestCase("conv.ovf.i4.un",
                Inst.Conv_Ovf_I4_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I4_Un)
                ),

            CreateTestCase("conv.ovf.i8.un",
                Inst.Conv_Ovf_I8_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I8_Un)
                ),

            CreateTestCase("conv.ovf.u1.un",
                Inst.Conv_Ovf_U1_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U1_Un)
                ),

            CreateTestCase("conv.ovf.u2.un",
                Inst.Conv_Ovf_U2_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U2_Un)
                ),

            CreateTestCase("conv.ovf.u4.un",
                Inst.Conv_Ovf_U4_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U4_Un)
                ),

            CreateTestCase("conv.ovf.u8.un",
                Inst.Conv_Ovf_U8_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U8_Un)
                ),

            CreateTestCase("conv.ovf.i.un",
                Inst.Conv_Ovf_I_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I_Un)
                ),

            CreateTestCase("conv.ovf.u.un",
                Inst.Conv_Ovf_U_Un(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U_Un)
                ),

            CreateTestCase("box",
                Inst.Box(MockType.Type),
                gen => gen.Emit(OpCodes.Box, MockType.Type)
                ),

            CreateTestCase("newarr",
                Inst.Newarr(MockType.Type),
                gen => gen.Emit(OpCodes.Newarr, MockType.Type)
                ),

            CreateTestCase("ldlen",
                Inst.Ldlen(),
                gen => gen.Emit(OpCodes.Ldlen)
                ),

            CreateTestCase("ldelema",
                Inst.Ldelema(MockType.Type),
                gen => gen.Emit(OpCodes.Ldelema, MockType.Type)
                ),

            CreateTestCase("ldelem.i1",
                Inst.Ldelem_I1(),
                gen => gen.Emit(OpCodes.Ldelem_I1)
                ),

            CreateTestCase("ldelem.u1",
                Inst.Ldelem_U1(),
                gen => gen.Emit(OpCodes.Ldelem_U1)
                ),

            CreateTestCase("ldelem.i2",
                Inst.Ldelem_I2(),
                gen => gen.Emit(OpCodes.Ldelem_I2)
                ),

            CreateTestCase("ldelem.u2",
                Inst.Ldelem_U2(),
                gen => gen.Emit(OpCodes.Ldelem_U2)
                ),

            CreateTestCase("ldelem.i4",
                Inst.Ldelem_I4(),
                gen => gen.Emit(OpCodes.Ldelem_I4)
                ),

            CreateTestCase("ldelem.u4",
                Inst.Ldelem_U4(),
                gen => gen.Emit(OpCodes.Ldelem_U4)
                ),

            CreateTestCase("ldelem.i8",
                Inst.Ldelem_I8(),
                gen => gen.Emit(OpCodes.Ldelem_I8)
                ),

            CreateTestCase("ldelem.i",
                Inst.Ldelem_I(),
                gen => gen.Emit(OpCodes.Ldelem_I)
                ),

            CreateTestCase("ldelem.r4",
                Inst.Ldelem_R4(),
                gen => gen.Emit(OpCodes.Ldelem_R4)
                ),

            CreateTestCase("ldelem.r8",
                Inst.Ldelem_R8(),
                gen => gen.Emit(OpCodes.Ldelem_R8)
                ),

            CreateTestCase("ldelem.ref",
                Inst.Ldelem_Ref(),
                gen => gen.Emit(OpCodes.Ldelem_Ref)
                ),

            CreateTestCase("stelem.i",
                Inst.Stelem_I(),
                gen => gen.Emit(OpCodes.Stelem_I)
                ),

            CreateTestCase("stelem.i1",
                Inst.Stelem_I1(),
                gen => gen.Emit(OpCodes.Stelem_I1)
                ),

            CreateTestCase("stelem.i2",
                Inst.Stelem_I2(),
                gen => gen.Emit(OpCodes.Stelem_I2)
                ),

            CreateTestCase("stelem.i4",
                Inst.Stelem_I4(),
                gen => gen.Emit(OpCodes.Stelem_I4)
                ),

            CreateTestCase("stelem.i8",
                Inst.Stelem_I8(),
                gen => gen.Emit(OpCodes.Stelem_I8)
                ),

            CreateTestCase("stelem.r4",
                Inst.Stelem_R4(),
                gen => gen.Emit(OpCodes.Stelem_R4)
                ),

            CreateTestCase("stelem.r8",
                Inst.Stelem_R8(),
                gen => gen.Emit(OpCodes.Stelem_R8)
                ),

            CreateTestCase("stelem.ref",
                Inst.Stelem_Ref(),
                gen => gen.Emit(OpCodes.Stelem_Ref)
                ),

            CreateTestCase("ldelem",
                Inst.Ldelem(MockType.Type),
                gen => gen.Emit(OpCodes.Ldelem, MockType.Type)
                ),

            CreateTestCase("stelem",
                Inst.Stelem(MockType.Type),
                gen => gen.Emit(OpCodes.Stelem, MockType.Type)
                ),

            CreateTestCase("unbox.any",
                Inst.Unbox_Any(MockType.Type),
                gen => gen.Emit(OpCodes.Unbox_Any, MockType.Type)
                ),

            CreateTestCase("conv.ovf.i1",
                Inst.Conv_Ovf_I1(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I1)
                ),

            CreateTestCase("conv.ovf.u1",
                Inst.Conv_Ovf_U1(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U1)
                ),

            CreateTestCase("conv.ovf.i2",
                Inst.Conv_Ovf_I2(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I2)
                ),

            CreateTestCase("conv.ovf.u2",
                Inst.Conv_Ovf_U2(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U2)
                ),

            CreateTestCase("conv.ovf.i4",
                Inst.Conv_Ovf_I4(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I4)
                ),

            CreateTestCase("conv.ovf.u4",
                Inst.Conv_Ovf_U4(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U4)
                ),

            CreateTestCase("conv.ovf.i8",
                Inst.Conv_Ovf_I8(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I8)
                ),

            CreateTestCase("conv.ovf.u8",
                Inst.Conv_Ovf_U8(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U8)
                ),

            CreateTestCase("refanyval",
                Inst.Refanyval(MockType.Type),
                gen => gen.Emit(OpCodes.Refanyval, MockType.Type)
                ),

            CreateTestCase("ckfinite",
                Inst.Ckfinite(),
                gen => gen.Emit(OpCodes.Ckfinite)
                ),

            CreateTestCase("mkrefany",
                Inst.Mkrefany(MockType.Type),
                gen => gen.Emit(OpCodes.Mkrefany, MockType.Type)
                ),

            CreateTestCase("conv.u2",
                Inst.Conv_U2(),
                gen => gen.Emit(OpCodes.Conv_U2)
                ),

            CreateTestCase("conv.u1",
                Inst.Conv_U1(),
                gen => gen.Emit(OpCodes.Conv_U1)
                ),

            CreateTestCase("conv.i",
                Inst.Conv_I(),
                gen => gen.Emit(OpCodes.Conv_I)
                ),

            CreateTestCase("conv.ovf.i",
                Inst.Conv_Ovf_I(),
                gen => gen.Emit(OpCodes.Conv_Ovf_I)
                ),

            CreateTestCase("conv.ovf.u",
                Inst.Conv_Ovf_U(),
                gen => gen.Emit(OpCodes.Conv_Ovf_U)
                ),

            CreateTestCase("add.ovf",
                Inst.Add_Ovf(),
                gen => gen.Emit(OpCodes.Add_Ovf)
                ),

            CreateTestCase("add.ovf.un",
                Inst.Add_Ovf_Un(),
                gen => gen.Emit(OpCodes.Add_Ovf_Un)
                ),

            CreateTestCase("mul.ovf",
                Inst.Mul_Ovf(),
                gen => gen.Emit(OpCodes.Mul_Ovf)
                ),

            CreateTestCase("mul.ovf.un",
                Inst.Mul_Ovf_Un(),
                gen => gen.Emit(OpCodes.Mul_Ovf_Un)
                ),

            CreateTestCase("sub.ovf",
                Inst.Sub_Ovf(),
                gen => gen.Emit(OpCodes.Sub_Ovf)
                ),

            CreateTestCase("sub.ovf.un",
                Inst.Sub_Ovf_Un(),
                gen => gen.Emit(OpCodes.Sub_Ovf_Un)
                ),

            CreateTestCase("endfinally",
                Inst.Endfinally(),
                gen => gen.Emit(OpCodes.Endfinally)
                ),

            CreateTestCase("stind.i",
                Inst.Stind_I(),
                gen => gen.Emit(OpCodes.Stind_I)
                ),

            CreateTestCase("conv.u",
                Inst.Conv_U(),
                gen => gen.Emit(OpCodes.Conv_U)
                ),

            CreateTestCase("arglist",
                Inst.Arglist(),
                gen => gen.Emit(OpCodes.Arglist)
                ),

            CreateTestCase("ceq",
                Inst.Ceq(),
                gen => gen.Emit(OpCodes.Ceq)
                ),

            CreateTestCase("cgt",
                Inst.Cgt(),
                gen => gen.Emit(OpCodes.Cgt)
                ),

            CreateTestCase("cgt.un",
                Inst.Cgt_Un(),
                gen => gen.Emit(OpCodes.Cgt_Un)
                ),

            CreateTestCase("clt",
                Inst.Clt(),
                gen => gen.Emit(OpCodes.Clt)
                ),

            CreateTestCase("clt.un",
                Inst.Clt_Un(),
                gen => gen.Emit(OpCodes.Clt_Un)
                ),

            CreateTestCase("ldftn",
                Inst.Ldftn(MockType.MethodInfo),
                gen => gen.Emit(OpCodes.Ldftn, MockType.MethodInfo)
                ),

            CreateTestCase("ldvirtftn",
                Inst.Ldvirtftn(MockType.MethodInfo),
                gen => gen.Emit(OpCodes.Ldvirtftn, MockType.MethodInfo)
                ),

            CreateTestCase("ldarg",
                Inst.Ldarg(ushort.MaxValue),
                gen => gen.Emit(OpCodes.Ldarg, unchecked((short)ushort.MaxValue))
                ),

            CreateTestCase("ldarga",
                Inst.Ldarga(ushort.MaxValue),
                gen => gen.Emit(OpCodes.Ldarga, unchecked((short)ushort.MaxValue))
                ),

            CreateTestCase("starg",
                Inst.Starg(ushort.MaxValue),
                gen => gen.Emit(OpCodes.Starg, unchecked((short)ushort.MaxValue))
                ),

            CreateTestCase("ldloc",
                Inst.Ldloc(ushort.MaxValue),
                gen => gen.Emit(OpCodes.Ldloc, unchecked((short)ushort.MaxValue))
                ),

            CreateTestCase("ldloca",
                Inst.Ldloca(ushort.MaxValue),
                gen => gen.Emit(OpCodes.Ldloca, unchecked((short)ushort.MaxValue))
                ),

            CreateTestCase("stloc",
                Inst.Stloc(ushort.MaxValue),
                gen => gen.Emit(OpCodes.Stloc, unchecked((short)ushort.MaxValue))
                ),

            CreateTestCase("localloc",
                Inst.Localloc(),
                gen => gen.Emit(OpCodes.Localloc)
                ),

            CreateTestCase("endfilter",
                Inst.Endfilter(),
                gen => gen.Emit(OpCodes.Endfilter)
                ),

            CreateTestCase("unaligned.",
                Inst.Unaligned(byte.MaxValue),
                gen => gen.Emit(OpCodes.Unaligned, byte.MaxValue)
                ),

            CreateTestCase("volatile.",
                Inst.Volatile(),
                gen => gen.Emit(OpCodes.Volatile)
                ),

            CreateTestCase("tail.",
                Inst.Tailcall(),
                gen => gen.Emit(OpCodes.Tailcall)
                ),

            CreateTestCase("initobj",
                Inst.Initobj(MockType.Type),
                gen => gen.Emit(OpCodes.Initobj, MockType.Type)
                ),

            CreateTestCase("constrained.",
                Inst.Constrained(MockType.Type),
                gen => gen.Emit(OpCodes.Constrained, MockType.Type)
                ),

            CreateTestCase("cpblk",
                Inst.Cpblk(),
                gen => gen.Emit(OpCodes.Cpblk)
                ),

            CreateTestCase("initblk",
                Inst.Initblk(),
                gen => gen.Emit(OpCodes.Initblk)
                ),

            CreateTestCase("rethrow",
                Inst.Rethrow(),
                gen => gen.Emit(OpCodes.Rethrow)
                ),

            CreateTestCase("sizeof",
                Inst.Sizeof(MockType.Type),
                gen => gen.Emit(OpCodes.Sizeof, MockType.Type)
                ),

            CreateTestCase("refanytype",
                Inst.Refanytype(),
                gen => gen.Emit(OpCodes.Refanytype)
                ),

            CreateTestCase("readonly.",
                Inst.Readonly(),
                gen => gen.Emit(OpCodes.Readonly)
                ),

            ];
    }
}
