// <auto-generated>
// THIS (.g.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using Xunit;

namespace PowerEmit
{
    public partial class PushOperationTest
    {
        [Theory]
        [MemberData(nameof(TestArgs_Branch))]
        private void PushTest_Branch(TestCase testCase)
            => PushTestCore(testCase);

            
        public static IEnumerable<object[]> TestArgs_Branch()
        {
            static Action<ILGenerator> createExpStream_BrToLeading(OpCode opcode, int offset)
                => gen =>
                {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = 0; i < offset; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(opcode, label);
                };
            static Action<ILGenerator> createExpStream_BrToFollowing(OpCode opcode, int offset)
                => gen =>
                {
                    var label = gen.DefineLabel();
                    gen.Emit(opcode, label);
                    for(var i = 0; i < offset; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };
            static Action<MethodDescription> createActStream_BrToLeading(Action<MethodDescription, LabelDescriptor> push, int offset)
                => desc =>
                {
                    var label = desc.AddLabel("label");
                    desc.Stream.Add(NoOpCode.MarkLabel(label));
                    for(var i = 0; i < offset; ++i)
                        desc.Stream.Add(OpCodeX.Nop());
                    push(desc, label);
                };
            static Action<MethodDescription> createActStream_BrToFollowing(Action<MethodDescription, LabelDescriptor> push, int offset)
                => desc =>
                {
                    var label = desc.AddLabel("label");
                    push(desc, label);
                    for(var i = 0; i < offset; ++i)
                        desc.Stream.Add(OpCodeX.Nop());
                    desc.Stream.Add(NoOpCode.MarkLabel(label));
                };


            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Br_S,
                    createExpStream_BrToLeading(OpCodes.Br_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Br_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Br_S,
                    createExpStream_BrToFollowing(OpCodes.Br_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Br_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Brfalse_S,
                    createExpStream_BrToLeading(OpCodes.Brfalse_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Brfalse_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Brfalse_S,
                    createExpStream_BrToFollowing(OpCodes.Brfalse_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Brfalse_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Brtrue_S,
                    createExpStream_BrToLeading(OpCodes.Brtrue_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Brtrue_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Brtrue_S,
                    createExpStream_BrToFollowing(OpCodes.Brtrue_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Brtrue_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Beq_S,
                    createExpStream_BrToLeading(OpCodes.Beq_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Beq_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Beq_S,
                    createExpStream_BrToFollowing(OpCodes.Beq_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Beq_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Bge_S,
                    createExpStream_BrToLeading(OpCodes.Bge_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bge_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bge_S,
                    createExpStream_BrToFollowing(OpCodes.Bge_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bge_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Bgt_S,
                    createExpStream_BrToLeading(OpCodes.Bgt_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bgt_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bgt_S,
                    createExpStream_BrToFollowing(OpCodes.Bgt_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bgt_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Ble_S,
                    createExpStream_BrToLeading(OpCodes.Ble_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Ble_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Ble_S,
                    createExpStream_BrToFollowing(OpCodes.Ble_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Ble_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Blt_S,
                    createExpStream_BrToLeading(OpCodes.Blt_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Blt_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Blt_S,
                    createExpStream_BrToFollowing(OpCodes.Blt_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Blt_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Bne_Un_S,
                    createExpStream_BrToLeading(OpCodes.Bne_Un_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bne_Un_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bne_Un_S,
                    createExpStream_BrToFollowing(OpCodes.Bne_Un_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bne_Un_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Bge_Un_S,
                    createExpStream_BrToLeading(OpCodes.Bge_Un_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bge_Un_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bge_Un_S,
                    createExpStream_BrToFollowing(OpCodes.Bge_Un_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bge_Un_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Bgt_Un_S,
                    createExpStream_BrToLeading(OpCodes.Bgt_Un_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bgt_Un_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bgt_Un_S,
                    createExpStream_BrToFollowing(OpCodes.Bgt_Un_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bgt_Un_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Ble_Un_S,
                    createExpStream_BrToLeading(OpCodes.Ble_Un_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Ble_Un_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Ble_Un_S,
                    createExpStream_BrToFollowing(OpCodes.Ble_Un_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Ble_Un_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Blt_Un_S,
                    createExpStream_BrToLeading(OpCodes.Blt_Un_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Blt_Un_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Blt_Un_S,
                    createExpStream_BrToFollowing(OpCodes.Blt_Un_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Blt_Un_S(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Br,
                    createExpStream_BrToLeading(OpCodes.Br, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Br(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Br,
                    createExpStream_BrToFollowing(OpCodes.Br, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Br(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Brfalse,
                    createExpStream_BrToLeading(OpCodes.Brfalse, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Brfalse(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Brfalse,
                    createExpStream_BrToFollowing(OpCodes.Brfalse, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Brfalse(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Brtrue,
                    createExpStream_BrToLeading(OpCodes.Brtrue, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Brtrue(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Brtrue,
                    createExpStream_BrToFollowing(OpCodes.Brtrue, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Brtrue(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Beq,
                    createExpStream_BrToLeading(OpCodes.Beq, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Beq(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Beq,
                    createExpStream_BrToFollowing(OpCodes.Beq, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Beq(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Bge,
                    createExpStream_BrToLeading(OpCodes.Bge, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bge(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bge,
                    createExpStream_BrToFollowing(OpCodes.Bge, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bge(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Bgt,
                    createExpStream_BrToLeading(OpCodes.Bgt, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bgt(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bgt,
                    createExpStream_BrToFollowing(OpCodes.Bgt, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bgt(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Ble,
                    createExpStream_BrToLeading(OpCodes.Ble, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Ble(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Ble,
                    createExpStream_BrToFollowing(OpCodes.Ble, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Ble(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Blt,
                    createExpStream_BrToLeading(OpCodes.Blt, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Blt(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Blt,
                    createExpStream_BrToFollowing(OpCodes.Blt, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Blt(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Bne_Un,
                    createExpStream_BrToLeading(OpCodes.Bne_Un, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bne_Un(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bne_Un,
                    createExpStream_BrToFollowing(OpCodes.Bne_Un, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bne_Un(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Bge_Un,
                    createExpStream_BrToLeading(OpCodes.Bge_Un, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bge_Un(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bge_Un,
                    createExpStream_BrToFollowing(OpCodes.Bge_Un, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bge_Un(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Bgt_Un,
                    createExpStream_BrToLeading(OpCodes.Bgt_Un, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Bgt_Un(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Bgt_Un,
                    createExpStream_BrToFollowing(OpCodes.Bgt_Un, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Bgt_Un(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Ble_Un,
                    createExpStream_BrToLeading(OpCodes.Ble_Un, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Ble_Un(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Ble_Un,
                    createExpStream_BrToFollowing(OpCodes.Ble_Un, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Ble_Un(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Blt_Un,
                    createExpStream_BrToLeading(OpCodes.Blt_Un, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Blt_Un(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Blt_Un,
                    createExpStream_BrToFollowing(OpCodes.Blt_Un, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Blt_Un(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 127, 255, 256, 1024})
            {
                yield return CreateArgs(
                    OpCodes.Leave,
                    createExpStream_BrToLeading(OpCodes.Leave, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Leave(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Leave,
                    createExpStream_BrToFollowing(OpCodes.Leave, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Leave(label)), i)
                );
            }

            foreach(var i in new []{0, 1, 2, 16, 126})
            {
                yield return CreateArgs(
                    OpCodes.Leave_S,
                    createExpStream_BrToLeading(OpCodes.Leave_S, i),
                    createActStream_BrToLeading((desc, label) => desc.Stream.Add(OpCodeX.Leave_S(label)), i)
                );
                yield return CreateArgs(
                    OpCodes.Leave_S,
                    createExpStream_BrToFollowing(OpCodes.Leave_S, i),
                    createActStream_BrToFollowing((desc, label) => desc.Stream.Add(OpCodeX.Leave_S(label)), i)
                );
            }
        }
    }
}
