// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using Xunit;

namespace PowerEmit.Disassemblers
{
    public partial class ILDisassemblerTest
    {
        [Theory]
        [MemberData(nameof(GetTestCases_Branch))]
        public void Disassemble_Branch(TestCase testCase)
            => DisassembleCore(testCase);


        public static IEnumerable<object[]> GetTestCases_Branch()
        {
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Br_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"br.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Br_S, label);
                };

                yield return CreateTestCase(
                    $"br.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Br_S, label);
                };

                yield return CreateTestCase(
                    $"br.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Br_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"br.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Br_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"br.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Br, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"br 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Br, label);
                };

                yield return CreateTestCase(
                    $"br -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Br, label);
                };

                yield return CreateTestCase(
                    $"br -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Br, label);
                };

                yield return CreateTestCase(
                    $"br -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Br, label);
                };

                yield return CreateTestCase(
                    $"br -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Br, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"br 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Br, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"br 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Br, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"br 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Br, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"br 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brfalse_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brfalse.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brfalse_S, label);
                };

                yield return CreateTestCase(
                    $"brfalse.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brfalse_S, label);
                };

                yield return CreateTestCase(
                    $"brfalse.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brfalse_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brfalse.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brfalse_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brfalse.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brfalse, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brfalse 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brfalse, label);
                };

                yield return CreateTestCase(
                    $"brfalse -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brfalse, label);
                };

                yield return CreateTestCase(
                    $"brfalse -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brfalse, label);
                };

                yield return CreateTestCase(
                    $"brfalse -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brfalse, label);
                };

                yield return CreateTestCase(
                    $"brfalse -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brfalse, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brfalse 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brfalse, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brfalse 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brfalse, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brfalse 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brfalse, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brfalse 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brtrue_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brtrue.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brtrue_S, label);
                };

                yield return CreateTestCase(
                    $"brtrue.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brtrue_S, label);
                };

                yield return CreateTestCase(
                    $"brtrue.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brtrue_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brtrue.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brtrue_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brtrue.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brtrue, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brtrue 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brtrue, label);
                };

                yield return CreateTestCase(
                    $"brtrue -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brtrue, label);
                };

                yield return CreateTestCase(
                    $"brtrue -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brtrue, label);
                };

                yield return CreateTestCase(
                    $"brtrue -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Brtrue, label);
                };

                yield return CreateTestCase(
                    $"brtrue -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brtrue, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brtrue 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brtrue, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brtrue 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brtrue, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brtrue 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Brtrue, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"brtrue 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Beq_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"beq.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Beq_S, label);
                };

                yield return CreateTestCase(
                    $"beq.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Beq_S, label);
                };

                yield return CreateTestCase(
                    $"beq.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Beq_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"beq.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Beq_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"beq.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Beq, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"beq 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Beq, label);
                };

                yield return CreateTestCase(
                    $"beq -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Beq, label);
                };

                yield return CreateTestCase(
                    $"beq -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Beq, label);
                };

                yield return CreateTestCase(
                    $"beq -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Beq, label);
                };

                yield return CreateTestCase(
                    $"beq -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Beq, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"beq 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Beq, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"beq 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Beq, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"beq 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Beq, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"beq 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge_S, label);
                };

                yield return CreateTestCase(
                    $"bge.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge_S, label);
                };

                yield return CreateTestCase(
                    $"bge.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge, label);
                };

                yield return CreateTestCase(
                    $"bge -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge, label);
                };

                yield return CreateTestCase(
                    $"bge -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge, label);
                };

                yield return CreateTestCase(
                    $"bge -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge, label);
                };

                yield return CreateTestCase(
                    $"bge -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt_S, label);
                };

                yield return CreateTestCase(
                    $"bgt.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt_S, label);
                };

                yield return CreateTestCase(
                    $"bgt.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt, label);
                };

                yield return CreateTestCase(
                    $"bgt -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt, label);
                };

                yield return CreateTestCase(
                    $"bgt -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt, label);
                };

                yield return CreateTestCase(
                    $"bgt -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt, label);
                };

                yield return CreateTestCase(
                    $"bgt -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble_S, label);
                };

                yield return CreateTestCase(
                    $"ble.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble_S, label);
                };

                yield return CreateTestCase(
                    $"ble.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble, label);
                };

                yield return CreateTestCase(
                    $"ble -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble, label);
                };

                yield return CreateTestCase(
                    $"ble -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble, label);
                };

                yield return CreateTestCase(
                    $"ble -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble, label);
                };

                yield return CreateTestCase(
                    $"ble -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt_S, label);
                };

                yield return CreateTestCase(
                    $"blt.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt_S, label);
                };

                yield return CreateTestCase(
                    $"blt.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt, label);
                };

                yield return CreateTestCase(
                    $"blt -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt, label);
                };

                yield return CreateTestCase(
                    $"blt -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt, label);
                };

                yield return CreateTestCase(
                    $"blt -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt, label);
                };

                yield return CreateTestCase(
                    $"blt -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bne_Un_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bne.un.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bne_Un_S, label);
                };

                yield return CreateTestCase(
                    $"bne.un.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bne_Un_S, label);
                };

                yield return CreateTestCase(
                    $"bne.un.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bne_Un_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bne.un.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bne_Un_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bne.un.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bne_Un, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bne.un 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bne_Un, label);
                };

                yield return CreateTestCase(
                    $"bne.un -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bne_Un, label);
                };

                yield return CreateTestCase(
                    $"bne.un -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bne_Un, label);
                };

                yield return CreateTestCase(
                    $"bne.un -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bne_Un, label);
                };

                yield return CreateTestCase(
                    $"bne.un -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bne_Un, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bne.un 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bne_Un, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bne.un 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bne_Un, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bne.un 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bne_Un, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bne.un 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_Un_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.un.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge_Un_S, label);
                };

                yield return CreateTestCase(
                    $"bge.un.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge_Un_S, label);
                };

                yield return CreateTestCase(
                    $"bge.un.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_Un_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.un.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_Un_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.un.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_Un, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.un 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge_Un, label);
                };

                yield return CreateTestCase(
                    $"bge.un -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge_Un, label);
                };

                yield return CreateTestCase(
                    $"bge.un -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge_Un, label);
                };

                yield return CreateTestCase(
                    $"bge.un -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bge_Un, label);
                };

                yield return CreateTestCase(
                    $"bge.un -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_Un, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.un 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_Un, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.un 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_Un, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.un 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bge_Un, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bge.un 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_Un_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.un.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt_Un_S, label);
                };

                yield return CreateTestCase(
                    $"bgt.un.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt_Un_S, label);
                };

                yield return CreateTestCase(
                    $"bgt.un.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_Un_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.un.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_Un_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.un.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_Un, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.un 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt_Un, label);
                };

                yield return CreateTestCase(
                    $"bgt.un -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt_Un, label);
                };

                yield return CreateTestCase(
                    $"bgt.un -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt_Un, label);
                };

                yield return CreateTestCase(
                    $"bgt.un -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Bgt_Un, label);
                };

                yield return CreateTestCase(
                    $"bgt.un -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_Un, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.un 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_Un, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.un 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_Un, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.un 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Bgt_Un, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"bgt.un 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_Un_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.un.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble_Un_S, label);
                };

                yield return CreateTestCase(
                    $"ble.un.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble_Un_S, label);
                };

                yield return CreateTestCase(
                    $"ble.un.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_Un_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.un.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_Un_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.un.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_Un, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.un 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble_Un, label);
                };

                yield return CreateTestCase(
                    $"ble.un -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble_Un, label);
                };

                yield return CreateTestCase(
                    $"ble.un -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble_Un, label);
                };

                yield return CreateTestCase(
                    $"ble.un -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Ble_Un, label);
                };

                yield return CreateTestCase(
                    $"ble.un -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_Un, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.un 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_Un, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.un 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_Un, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.un 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Ble_Un, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"ble.un 32767",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_Un_S, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.un.s 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -3; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt_Un_S, label);
                };

                yield return CreateTestCase(
                    $"blt.un.s -3",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -2; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt_Un_S, label);
                };

                yield return CreateTestCase(
                    $"blt.un.s -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_Un_S, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.un.s 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_Un_S, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.un.s 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_Un, label);
                    for(var i = 0; i < 0; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.un 0",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -6; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt_Un, label);
                };

                yield return CreateTestCase(
                    $"blt.un -6",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -128; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt_Un, label);
                };

                yield return CreateTestCase(
                    $"blt.un -128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -129; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt_Un, label);
                };

                yield return CreateTestCase(
                    $"blt.un -129",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.MarkLabel(label);
                    for(var i = -5; i > -32768; --i)
                        gen.Emit(OpCodes.Nop);
                    gen.Emit(OpCodes.Blt_Un, label);
                };

                yield return CreateTestCase(
                    $"blt.un -32768",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_Un, label);
                    for(var i = 0; i < 1; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.un 1",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_Un, label);
                    for(var i = 0; i < 127; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.un 127",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_Un, label);
                    for(var i = 0; i < 128; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.un 128",
                    expected);
            }
            {
                Action<ILGenerator> expected = gen => {
                    var label = gen.DefineLabel();
                    gen.Emit(OpCodes.Blt_Un, label);
                    for(var i = 0; i < 32767; ++i)
                        gen.Emit(OpCodes.Nop);
                    gen.MarkLabel(label);
                };

                yield return CreateTestCase(
                    $"blt.un 32767",
                    expected);
            }
            yield break;
        }
    }
}
