// <auto-generated>
// THIS (.g.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System;
using System.Collections.Immutable;
using System.Reflection.Emit;

namespace PowerEmit;

/// <summary>
/// Provides constants for all IL opcodes defined in <see cref="OpCodes"/>.
/// </summary>
public static class OpCodeConst
{
    #pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public const short Nop            = 0;
    public const short Break          = 1;
    public const short Ldarg_0        = 2;
    public const short Ldarg_1        = 3;
    public const short Ldarg_2        = 4;
    public const short Ldarg_3        = 5;
    public const short Ldloc_0        = 6;
    public const short Ldloc_1        = 7;
    public const short Ldloc_2        = 8;
    public const short Ldloc_3        = 9;
    public const short Stloc_0        = 10;
    public const short Stloc_1        = 11;
    public const short Stloc_2        = 12;
    public const short Stloc_3        = 13;
    public const short Ldarg_S        = 14;
    public const short Ldarga_S       = 15;
    public const short Starg_S        = 16;
    public const short Ldloc_S        = 17;
    public const short Ldloca_S       = 18;
    public const short Stloc_S        = 19;
    public const short Ldnull         = 20;
    public const short Ldc_I4_M1      = 21;
    public const short Ldc_I4_0       = 22;
    public const short Ldc_I4_1       = 23;
    public const short Ldc_I4_2       = 24;
    public const short Ldc_I4_3       = 25;
    public const short Ldc_I4_4       = 26;
    public const short Ldc_I4_5       = 27;
    public const short Ldc_I4_6       = 28;
    public const short Ldc_I4_7       = 29;
    public const short Ldc_I4_8       = 30;
    public const short Ldc_I4_S       = 31;
    public const short Ldc_I4         = 32;
    public const short Ldc_I8         = 33;
    public const short Ldc_R4         = 34;
    public const short Ldc_R8         = 35;
    public const short Dup            = 37;
    public const short Pop            = 38;
    public const short Jmp            = 39;
    public const short Call           = 40;
    public const short Calli          = 41;
    public const short Ret            = 42;
    public const short Br_S           = 43;
    public const short Brfalse_S      = 44;
    public const short Brtrue_S       = 45;
    public const short Beq_S          = 46;
    public const short Bge_S          = 47;
    public const short Bgt_S          = 48;
    public const short Ble_S          = 49;
    public const short Blt_S          = 50;
    public const short Bne_Un_S       = 51;
    public const short Bge_Un_S       = 52;
    public const short Bgt_Un_S       = 53;
    public const short Ble_Un_S       = 54;
    public const short Blt_Un_S       = 55;
    public const short Br             = 56;
    public const short Brfalse        = 57;
    public const short Brtrue         = 58;
    public const short Beq            = 59;
    public const short Bge            = 60;
    public const short Bgt            = 61;
    public const short Ble            = 62;
    public const short Blt            = 63;
    public const short Bne_Un         = 64;
    public const short Bge_Un         = 65;
    public const short Bgt_Un         = 66;
    public const short Ble_Un         = 67;
    public const short Blt_Un         = 68;
    public const short Switch         = 69;
    public const short Ldind_I1       = 70;
    public const short Ldind_U1       = 71;
    public const short Ldind_I2       = 72;
    public const short Ldind_U2       = 73;
    public const short Ldind_I4       = 74;
    public const short Ldind_U4       = 75;
    public const short Ldind_I8       = 76;
    public const short Ldind_I        = 77;
    public const short Ldind_R4       = 78;
    public const short Ldind_R8       = 79;
    public const short Ldind_Ref      = 80;
    public const short Stind_Ref      = 81;
    public const short Stind_I1       = 82;
    public const short Stind_I2       = 83;
    public const short Stind_I4       = 84;
    public const short Stind_I8       = 85;
    public const short Stind_R4       = 86;
    public const short Stind_R8       = 87;
    public const short Add            = 88;
    public const short Sub            = 89;
    public const short Mul            = 90;
    public const short Div            = 91;
    public const short Div_Un         = 92;
    public const short Rem            = 93;
    public const short Rem_Un         = 94;
    public const short And            = 95;
    public const short Or             = 96;
    public const short Xor            = 97;
    public const short Shl            = 98;
    public const short Shr            = 99;
    public const short Shr_Un         = 100;
    public const short Neg            = 101;
    public const short Not            = 102;
    public const short Conv_I1        = 103;
    public const short Conv_I2        = 104;
    public const short Conv_I4        = 105;
    public const short Conv_I8        = 106;
    public const short Conv_R4        = 107;
    public const short Conv_R8        = 108;
    public const short Conv_U4        = 109;
    public const short Conv_U8        = 110;
    public const short Callvirt       = 111;
    public const short Cpobj          = 112;
    public const short Ldobj          = 113;
    public const short Ldstr          = 114;
    public const short Newobj         = 115;
    public const short Castclass      = 116;
    public const short Isinst         = 117;
    public const short Conv_R_Un      = 118;
    public const short Unbox          = 121;
    public const short Throw          = 122;
    public const short Ldfld          = 123;
    public const short Ldflda         = 124;
    public const short Stfld          = 125;
    public const short Ldsfld         = 126;
    public const short Ldsflda        = 127;
    public const short Stsfld         = 128;
    public const short Stobj          = 129;
    public const short Conv_Ovf_I1_Un = 130;
    public const short Conv_Ovf_I2_Un = 131;
    public const short Conv_Ovf_I4_Un = 132;
    public const short Conv_Ovf_I8_Un = 133;
    public const short Conv_Ovf_U1_Un = 134;
    public const short Conv_Ovf_U2_Un = 135;
    public const short Conv_Ovf_U4_Un = 136;
    public const short Conv_Ovf_U8_Un = 137;
    public const short Conv_Ovf_I_Un  = 138;
    public const short Conv_Ovf_U_Un  = 139;
    public const short Box            = 140;
    public const short Newarr         = 141;
    public const short Ldlen          = 142;
    public const short Ldelema        = 143;
    public const short Ldelem_I1      = 144;
    public const short Ldelem_U1      = 145;
    public const short Ldelem_I2      = 146;
    public const short Ldelem_U2      = 147;
    public const short Ldelem_I4      = 148;
    public const short Ldelem_U4      = 149;
    public const short Ldelem_I8      = 150;
    public const short Ldelem_I       = 151;
    public const short Ldelem_R4      = 152;
    public const short Ldelem_R8      = 153;
    public const short Ldelem_Ref     = 154;
    public const short Stelem_I       = 155;
    public const short Stelem_I1      = 156;
    public const short Stelem_I2      = 157;
    public const short Stelem_I4      = 158;
    public const short Stelem_I8      = 159;
    public const short Stelem_R4      = 160;
    public const short Stelem_R8      = 161;
    public const short Stelem_Ref     = 162;
    public const short Ldelem         = 163;
    public const short Stelem         = 164;
    public const short Unbox_Any      = 165;
    public const short Conv_Ovf_I1    = 179;
    public const short Conv_Ovf_U1    = 180;
    public const short Conv_Ovf_I2    = 181;
    public const short Conv_Ovf_U2    = 182;
    public const short Conv_Ovf_I4    = 183;
    public const short Conv_Ovf_U4    = 184;
    public const short Conv_Ovf_I8    = 185;
    public const short Conv_Ovf_U8    = 186;
    public const short Refanyval      = 194;
    public const short Ckfinite       = 195;
    public const short Mkrefany       = 198;
    public const short Ldtoken        = 208;
    public const short Conv_U2        = 209;
    public const short Conv_U1        = 210;
    public const short Conv_I         = 211;
    public const short Conv_Ovf_I     = 212;
    public const short Conv_Ovf_U     = 213;
    public const short Add_Ovf        = 214;
    public const short Add_Ovf_Un     = 215;
    public const short Mul_Ovf        = 216;
    public const short Mul_Ovf_Un     = 217;
    public const short Sub_Ovf        = 218;
    public const short Sub_Ovf_Un     = 219;
    public const short Endfinally     = 220;
    public const short Leave          = 221;
    public const short Leave_S        = 222;
    public const short Stind_I        = 223;
    public const short Conv_U         = 224;
    public const short Prefix7        = 248;
    public const short Prefix6        = 249;
    public const short Prefix5        = 250;
    public const short Prefix4        = 251;
    public const short Prefix3        = 252;
    public const short Prefix2        = 253;
    public const short Prefix1        = 254;
    public const short Prefixref      = 255;
    public const short Arglist        = -512;
    public const short Ceq            = -511;
    public const short Cgt            = -510;
    public const short Cgt_Un         = -509;
    public const short Clt            = -508;
    public const short Clt_Un         = -507;
    public const short Ldftn          = -506;
    public const short Ldvirtftn      = -505;
    public const short Ldarg          = -503;
    public const short Ldarga         = -502;
    public const short Starg          = -501;
    public const short Ldloc          = -500;
    public const short Ldloca         = -499;
    public const short Stloc          = -498;
    public const short Localloc       = -497;
    public const short Endfilter      = -495;
    public const short Unaligned      = -494;
    public const short Volatile       = -493;
    public const short Tailcall       = -492;
    public const short Initobj        = -491;
    public const short Constrained    = -490;
    public const short Cpblk          = -489;
    public const short Initblk        = -488;
    public const short Rethrow        = -486;
    public const short Sizeof         = -484;
    public const short Refanytype     = -483;
    public const short Readonly       = -482;
    #pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

    /// <summary>
    /// Gets the <see cref="OpCode"/> instance corresponding to the specified constant value.
    /// </summary>
    public static ImmutableDictionary<short, OpCode> OpCodes { get; } =
        ImmutableDictionary.CreateRange<short, OpCode>([
            new(Nop           , System.Reflection.Emit.OpCodes.Nop           ),
            new(Break         , System.Reflection.Emit.OpCodes.Break         ),
            new(Ldarg_0       , System.Reflection.Emit.OpCodes.Ldarg_0       ),
            new(Ldarg_1       , System.Reflection.Emit.OpCodes.Ldarg_1       ),
            new(Ldarg_2       , System.Reflection.Emit.OpCodes.Ldarg_2       ),
            new(Ldarg_3       , System.Reflection.Emit.OpCodes.Ldarg_3       ),
            new(Ldloc_0       , System.Reflection.Emit.OpCodes.Ldloc_0       ),
            new(Ldloc_1       , System.Reflection.Emit.OpCodes.Ldloc_1       ),
            new(Ldloc_2       , System.Reflection.Emit.OpCodes.Ldloc_2       ),
            new(Ldloc_3       , System.Reflection.Emit.OpCodes.Ldloc_3       ),
            new(Stloc_0       , System.Reflection.Emit.OpCodes.Stloc_0       ),
            new(Stloc_1       , System.Reflection.Emit.OpCodes.Stloc_1       ),
            new(Stloc_2       , System.Reflection.Emit.OpCodes.Stloc_2       ),
            new(Stloc_3       , System.Reflection.Emit.OpCodes.Stloc_3       ),
            new(Ldarg_S       , System.Reflection.Emit.OpCodes.Ldarg_S       ),
            new(Ldarga_S      , System.Reflection.Emit.OpCodes.Ldarga_S      ),
            new(Starg_S       , System.Reflection.Emit.OpCodes.Starg_S       ),
            new(Ldloc_S       , System.Reflection.Emit.OpCodes.Ldloc_S       ),
            new(Ldloca_S      , System.Reflection.Emit.OpCodes.Ldloca_S      ),
            new(Stloc_S       , System.Reflection.Emit.OpCodes.Stloc_S       ),
            new(Ldnull        , System.Reflection.Emit.OpCodes.Ldnull        ),
            new(Ldc_I4_M1     , System.Reflection.Emit.OpCodes.Ldc_I4_M1     ),
            new(Ldc_I4_0      , System.Reflection.Emit.OpCodes.Ldc_I4_0      ),
            new(Ldc_I4_1      , System.Reflection.Emit.OpCodes.Ldc_I4_1      ),
            new(Ldc_I4_2      , System.Reflection.Emit.OpCodes.Ldc_I4_2      ),
            new(Ldc_I4_3      , System.Reflection.Emit.OpCodes.Ldc_I4_3      ),
            new(Ldc_I4_4      , System.Reflection.Emit.OpCodes.Ldc_I4_4      ),
            new(Ldc_I4_5      , System.Reflection.Emit.OpCodes.Ldc_I4_5      ),
            new(Ldc_I4_6      , System.Reflection.Emit.OpCodes.Ldc_I4_6      ),
            new(Ldc_I4_7      , System.Reflection.Emit.OpCodes.Ldc_I4_7      ),
            new(Ldc_I4_8      , System.Reflection.Emit.OpCodes.Ldc_I4_8      ),
            new(Ldc_I4_S      , System.Reflection.Emit.OpCodes.Ldc_I4_S      ),
            new(Ldc_I4        , System.Reflection.Emit.OpCodes.Ldc_I4        ),
            new(Ldc_I8        , System.Reflection.Emit.OpCodes.Ldc_I8        ),
            new(Ldc_R4        , System.Reflection.Emit.OpCodes.Ldc_R4        ),
            new(Ldc_R8        , System.Reflection.Emit.OpCodes.Ldc_R8        ),
            new(Dup           , System.Reflection.Emit.OpCodes.Dup           ),
            new(Pop           , System.Reflection.Emit.OpCodes.Pop           ),
            new(Jmp           , System.Reflection.Emit.OpCodes.Jmp           ),
            new(Call          , System.Reflection.Emit.OpCodes.Call          ),
            new(Calli         , System.Reflection.Emit.OpCodes.Calli         ),
            new(Ret           , System.Reflection.Emit.OpCodes.Ret           ),
            new(Br_S          , System.Reflection.Emit.OpCodes.Br_S          ),
            new(Brfalse_S     , System.Reflection.Emit.OpCodes.Brfalse_S     ),
            new(Brtrue_S      , System.Reflection.Emit.OpCodes.Brtrue_S      ),
            new(Beq_S         , System.Reflection.Emit.OpCodes.Beq_S         ),
            new(Bge_S         , System.Reflection.Emit.OpCodes.Bge_S         ),
            new(Bgt_S         , System.Reflection.Emit.OpCodes.Bgt_S         ),
            new(Ble_S         , System.Reflection.Emit.OpCodes.Ble_S         ),
            new(Blt_S         , System.Reflection.Emit.OpCodes.Blt_S         ),
            new(Bne_Un_S      , System.Reflection.Emit.OpCodes.Bne_Un_S      ),
            new(Bge_Un_S      , System.Reflection.Emit.OpCodes.Bge_Un_S      ),
            new(Bgt_Un_S      , System.Reflection.Emit.OpCodes.Bgt_Un_S      ),
            new(Ble_Un_S      , System.Reflection.Emit.OpCodes.Ble_Un_S      ),
            new(Blt_Un_S      , System.Reflection.Emit.OpCodes.Blt_Un_S      ),
            new(Br            , System.Reflection.Emit.OpCodes.Br            ),
            new(Brfalse       , System.Reflection.Emit.OpCodes.Brfalse       ),
            new(Brtrue        , System.Reflection.Emit.OpCodes.Brtrue        ),
            new(Beq           , System.Reflection.Emit.OpCodes.Beq           ),
            new(Bge           , System.Reflection.Emit.OpCodes.Bge           ),
            new(Bgt           , System.Reflection.Emit.OpCodes.Bgt           ),
            new(Ble           , System.Reflection.Emit.OpCodes.Ble           ),
            new(Blt           , System.Reflection.Emit.OpCodes.Blt           ),
            new(Bne_Un        , System.Reflection.Emit.OpCodes.Bne_Un        ),
            new(Bge_Un        , System.Reflection.Emit.OpCodes.Bge_Un        ),
            new(Bgt_Un        , System.Reflection.Emit.OpCodes.Bgt_Un        ),
            new(Ble_Un        , System.Reflection.Emit.OpCodes.Ble_Un        ),
            new(Blt_Un        , System.Reflection.Emit.OpCodes.Blt_Un        ),
            new(Switch        , System.Reflection.Emit.OpCodes.Switch        ),
            new(Ldind_I1      , System.Reflection.Emit.OpCodes.Ldind_I1      ),
            new(Ldind_U1      , System.Reflection.Emit.OpCodes.Ldind_U1      ),
            new(Ldind_I2      , System.Reflection.Emit.OpCodes.Ldind_I2      ),
            new(Ldind_U2      , System.Reflection.Emit.OpCodes.Ldind_U2      ),
            new(Ldind_I4      , System.Reflection.Emit.OpCodes.Ldind_I4      ),
            new(Ldind_U4      , System.Reflection.Emit.OpCodes.Ldind_U4      ),
            new(Ldind_I8      , System.Reflection.Emit.OpCodes.Ldind_I8      ),
            new(Ldind_I       , System.Reflection.Emit.OpCodes.Ldind_I       ),
            new(Ldind_R4      , System.Reflection.Emit.OpCodes.Ldind_R4      ),
            new(Ldind_R8      , System.Reflection.Emit.OpCodes.Ldind_R8      ),
            new(Ldind_Ref     , System.Reflection.Emit.OpCodes.Ldind_Ref     ),
            new(Stind_Ref     , System.Reflection.Emit.OpCodes.Stind_Ref     ),
            new(Stind_I1      , System.Reflection.Emit.OpCodes.Stind_I1      ),
            new(Stind_I2      , System.Reflection.Emit.OpCodes.Stind_I2      ),
            new(Stind_I4      , System.Reflection.Emit.OpCodes.Stind_I4      ),
            new(Stind_I8      , System.Reflection.Emit.OpCodes.Stind_I8      ),
            new(Stind_R4      , System.Reflection.Emit.OpCodes.Stind_R4      ),
            new(Stind_R8      , System.Reflection.Emit.OpCodes.Stind_R8      ),
            new(Add           , System.Reflection.Emit.OpCodes.Add           ),
            new(Sub           , System.Reflection.Emit.OpCodes.Sub           ),
            new(Mul           , System.Reflection.Emit.OpCodes.Mul           ),
            new(Div           , System.Reflection.Emit.OpCodes.Div           ),
            new(Div_Un        , System.Reflection.Emit.OpCodes.Div_Un        ),
            new(Rem           , System.Reflection.Emit.OpCodes.Rem           ),
            new(Rem_Un        , System.Reflection.Emit.OpCodes.Rem_Un        ),
            new(And           , System.Reflection.Emit.OpCodes.And           ),
            new(Or            , System.Reflection.Emit.OpCodes.Or            ),
            new(Xor           , System.Reflection.Emit.OpCodes.Xor           ),
            new(Shl           , System.Reflection.Emit.OpCodes.Shl           ),
            new(Shr           , System.Reflection.Emit.OpCodes.Shr           ),
            new(Shr_Un        , System.Reflection.Emit.OpCodes.Shr_Un        ),
            new(Neg           , System.Reflection.Emit.OpCodes.Neg           ),
            new(Not           , System.Reflection.Emit.OpCodes.Not           ),
            new(Conv_I1       , System.Reflection.Emit.OpCodes.Conv_I1       ),
            new(Conv_I2       , System.Reflection.Emit.OpCodes.Conv_I2       ),
            new(Conv_I4       , System.Reflection.Emit.OpCodes.Conv_I4       ),
            new(Conv_I8       , System.Reflection.Emit.OpCodes.Conv_I8       ),
            new(Conv_R4       , System.Reflection.Emit.OpCodes.Conv_R4       ),
            new(Conv_R8       , System.Reflection.Emit.OpCodes.Conv_R8       ),
            new(Conv_U4       , System.Reflection.Emit.OpCodes.Conv_U4       ),
            new(Conv_U8       , System.Reflection.Emit.OpCodes.Conv_U8       ),
            new(Callvirt      , System.Reflection.Emit.OpCodes.Callvirt      ),
            new(Cpobj         , System.Reflection.Emit.OpCodes.Cpobj         ),
            new(Ldobj         , System.Reflection.Emit.OpCodes.Ldobj         ),
            new(Ldstr         , System.Reflection.Emit.OpCodes.Ldstr         ),
            new(Newobj        , System.Reflection.Emit.OpCodes.Newobj        ),
            new(Castclass     , System.Reflection.Emit.OpCodes.Castclass     ),
            new(Isinst        , System.Reflection.Emit.OpCodes.Isinst        ),
            new(Conv_R_Un     , System.Reflection.Emit.OpCodes.Conv_R_Un     ),
            new(Unbox         , System.Reflection.Emit.OpCodes.Unbox         ),
            new(Throw         , System.Reflection.Emit.OpCodes.Throw         ),
            new(Ldfld         , System.Reflection.Emit.OpCodes.Ldfld         ),
            new(Ldflda        , System.Reflection.Emit.OpCodes.Ldflda        ),
            new(Stfld         , System.Reflection.Emit.OpCodes.Stfld         ),
            new(Ldsfld        , System.Reflection.Emit.OpCodes.Ldsfld        ),
            new(Ldsflda       , System.Reflection.Emit.OpCodes.Ldsflda       ),
            new(Stsfld        , System.Reflection.Emit.OpCodes.Stsfld        ),
            new(Stobj         , System.Reflection.Emit.OpCodes.Stobj         ),
            new(Conv_Ovf_I1_Un, System.Reflection.Emit.OpCodes.Conv_Ovf_I1_Un),
            new(Conv_Ovf_I2_Un, System.Reflection.Emit.OpCodes.Conv_Ovf_I2_Un),
            new(Conv_Ovf_I4_Un, System.Reflection.Emit.OpCodes.Conv_Ovf_I4_Un),
            new(Conv_Ovf_I8_Un, System.Reflection.Emit.OpCodes.Conv_Ovf_I8_Un),
            new(Conv_Ovf_U1_Un, System.Reflection.Emit.OpCodes.Conv_Ovf_U1_Un),
            new(Conv_Ovf_U2_Un, System.Reflection.Emit.OpCodes.Conv_Ovf_U2_Un),
            new(Conv_Ovf_U4_Un, System.Reflection.Emit.OpCodes.Conv_Ovf_U4_Un),
            new(Conv_Ovf_U8_Un, System.Reflection.Emit.OpCodes.Conv_Ovf_U8_Un),
            new(Conv_Ovf_I_Un , System.Reflection.Emit.OpCodes.Conv_Ovf_I_Un ),
            new(Conv_Ovf_U_Un , System.Reflection.Emit.OpCodes.Conv_Ovf_U_Un ),
            new(Box           , System.Reflection.Emit.OpCodes.Box           ),
            new(Newarr        , System.Reflection.Emit.OpCodes.Newarr        ),
            new(Ldlen         , System.Reflection.Emit.OpCodes.Ldlen         ),
            new(Ldelema       , System.Reflection.Emit.OpCodes.Ldelema       ),
            new(Ldelem_I1     , System.Reflection.Emit.OpCodes.Ldelem_I1     ),
            new(Ldelem_U1     , System.Reflection.Emit.OpCodes.Ldelem_U1     ),
            new(Ldelem_I2     , System.Reflection.Emit.OpCodes.Ldelem_I2     ),
            new(Ldelem_U2     , System.Reflection.Emit.OpCodes.Ldelem_U2     ),
            new(Ldelem_I4     , System.Reflection.Emit.OpCodes.Ldelem_I4     ),
            new(Ldelem_U4     , System.Reflection.Emit.OpCodes.Ldelem_U4     ),
            new(Ldelem_I8     , System.Reflection.Emit.OpCodes.Ldelem_I8     ),
            new(Ldelem_I      , System.Reflection.Emit.OpCodes.Ldelem_I      ),
            new(Ldelem_R4     , System.Reflection.Emit.OpCodes.Ldelem_R4     ),
            new(Ldelem_R8     , System.Reflection.Emit.OpCodes.Ldelem_R8     ),
            new(Ldelem_Ref    , System.Reflection.Emit.OpCodes.Ldelem_Ref    ),
            new(Stelem_I      , System.Reflection.Emit.OpCodes.Stelem_I      ),
            new(Stelem_I1     , System.Reflection.Emit.OpCodes.Stelem_I1     ),
            new(Stelem_I2     , System.Reflection.Emit.OpCodes.Stelem_I2     ),
            new(Stelem_I4     , System.Reflection.Emit.OpCodes.Stelem_I4     ),
            new(Stelem_I8     , System.Reflection.Emit.OpCodes.Stelem_I8     ),
            new(Stelem_R4     , System.Reflection.Emit.OpCodes.Stelem_R4     ),
            new(Stelem_R8     , System.Reflection.Emit.OpCodes.Stelem_R8     ),
            new(Stelem_Ref    , System.Reflection.Emit.OpCodes.Stelem_Ref    ),
            new(Ldelem        , System.Reflection.Emit.OpCodes.Ldelem        ),
            new(Stelem        , System.Reflection.Emit.OpCodes.Stelem        ),
            new(Unbox_Any     , System.Reflection.Emit.OpCodes.Unbox_Any     ),
            new(Conv_Ovf_I1   , System.Reflection.Emit.OpCodes.Conv_Ovf_I1   ),
            new(Conv_Ovf_U1   , System.Reflection.Emit.OpCodes.Conv_Ovf_U1   ),
            new(Conv_Ovf_I2   , System.Reflection.Emit.OpCodes.Conv_Ovf_I2   ),
            new(Conv_Ovf_U2   , System.Reflection.Emit.OpCodes.Conv_Ovf_U2   ),
            new(Conv_Ovf_I4   , System.Reflection.Emit.OpCodes.Conv_Ovf_I4   ),
            new(Conv_Ovf_U4   , System.Reflection.Emit.OpCodes.Conv_Ovf_U4   ),
            new(Conv_Ovf_I8   , System.Reflection.Emit.OpCodes.Conv_Ovf_I8   ),
            new(Conv_Ovf_U8   , System.Reflection.Emit.OpCodes.Conv_Ovf_U8   ),
            new(Refanyval     , System.Reflection.Emit.OpCodes.Refanyval     ),
            new(Ckfinite      , System.Reflection.Emit.OpCodes.Ckfinite      ),
            new(Mkrefany      , System.Reflection.Emit.OpCodes.Mkrefany      ),
            new(Ldtoken       , System.Reflection.Emit.OpCodes.Ldtoken       ),
            new(Conv_U2       , System.Reflection.Emit.OpCodes.Conv_U2       ),
            new(Conv_U1       , System.Reflection.Emit.OpCodes.Conv_U1       ),
            new(Conv_I        , System.Reflection.Emit.OpCodes.Conv_I        ),
            new(Conv_Ovf_I    , System.Reflection.Emit.OpCodes.Conv_Ovf_I    ),
            new(Conv_Ovf_U    , System.Reflection.Emit.OpCodes.Conv_Ovf_U    ),
            new(Add_Ovf       , System.Reflection.Emit.OpCodes.Add_Ovf       ),
            new(Add_Ovf_Un    , System.Reflection.Emit.OpCodes.Add_Ovf_Un    ),
            new(Mul_Ovf       , System.Reflection.Emit.OpCodes.Mul_Ovf       ),
            new(Mul_Ovf_Un    , System.Reflection.Emit.OpCodes.Mul_Ovf_Un    ),
            new(Sub_Ovf       , System.Reflection.Emit.OpCodes.Sub_Ovf       ),
            new(Sub_Ovf_Un    , System.Reflection.Emit.OpCodes.Sub_Ovf_Un    ),
            new(Endfinally    , System.Reflection.Emit.OpCodes.Endfinally    ),
            new(Leave         , System.Reflection.Emit.OpCodes.Leave         ),
            new(Leave_S       , System.Reflection.Emit.OpCodes.Leave_S       ),
            new(Stind_I       , System.Reflection.Emit.OpCodes.Stind_I       ),
            new(Conv_U        , System.Reflection.Emit.OpCodes.Conv_U        ),
            new(Prefix7       , System.Reflection.Emit.OpCodes.Prefix7       ),
            new(Prefix6       , System.Reflection.Emit.OpCodes.Prefix6       ),
            new(Prefix5       , System.Reflection.Emit.OpCodes.Prefix5       ),
            new(Prefix4       , System.Reflection.Emit.OpCodes.Prefix4       ),
            new(Prefix3       , System.Reflection.Emit.OpCodes.Prefix3       ),
            new(Prefix2       , System.Reflection.Emit.OpCodes.Prefix2       ),
            new(Prefix1       , System.Reflection.Emit.OpCodes.Prefix1       ),
            new(Prefixref     , System.Reflection.Emit.OpCodes.Prefixref     ),
            new(Arglist       , System.Reflection.Emit.OpCodes.Arglist       ),
            new(Ceq           , System.Reflection.Emit.OpCodes.Ceq           ),
            new(Cgt           , System.Reflection.Emit.OpCodes.Cgt           ),
            new(Cgt_Un        , System.Reflection.Emit.OpCodes.Cgt_Un        ),
            new(Clt           , System.Reflection.Emit.OpCodes.Clt           ),
            new(Clt_Un        , System.Reflection.Emit.OpCodes.Clt_Un        ),
            new(Ldftn         , System.Reflection.Emit.OpCodes.Ldftn         ),
            new(Ldvirtftn     , System.Reflection.Emit.OpCodes.Ldvirtftn     ),
            new(Ldarg         , System.Reflection.Emit.OpCodes.Ldarg         ),
            new(Ldarga        , System.Reflection.Emit.OpCodes.Ldarga        ),
            new(Starg         , System.Reflection.Emit.OpCodes.Starg         ),
            new(Ldloc         , System.Reflection.Emit.OpCodes.Ldloc         ),
            new(Ldloca        , System.Reflection.Emit.OpCodes.Ldloca        ),
            new(Stloc         , System.Reflection.Emit.OpCodes.Stloc         ),
            new(Localloc      , System.Reflection.Emit.OpCodes.Localloc      ),
            new(Endfilter     , System.Reflection.Emit.OpCodes.Endfilter     ),
            new(Unaligned     , System.Reflection.Emit.OpCodes.Unaligned     ),
            new(Volatile      , System.Reflection.Emit.OpCodes.Volatile      ),
            new(Tailcall      , System.Reflection.Emit.OpCodes.Tailcall      ),
            new(Initobj       , System.Reflection.Emit.OpCodes.Initobj       ),
            new(Constrained   , System.Reflection.Emit.OpCodes.Constrained   ),
            new(Cpblk         , System.Reflection.Emit.OpCodes.Cpblk         ),
            new(Initblk       , System.Reflection.Emit.OpCodes.Initblk       ),
            new(Rethrow       , System.Reflection.Emit.OpCodes.Rethrow       ),
            new(Sizeof        , System.Reflection.Emit.OpCodes.Sizeof        ),
            new(Refanytype    , System.Reflection.Emit.OpCodes.Refanytype    ),
            new(Readonly      , System.Reflection.Emit.OpCodes.Readonly      ),
        ]);
}
