name: .NET Core CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: update submodules
      run: git submodule update --init --recursive

    - name: Restore dependencies
      run: dotnet restore PowerEmit.slnx

    - name: Build solution
      run: dotnet build PowerEmit.slnx --no-restore

    - name: Run tests
      run: dotnet test PowerEmit.slnx --no-build --verbosity normal
